version: '2.1'

networks:
  nw_services_db:
    ipam:
      config:
        - subnet: 172.111.111.0/24
  nw_nodes_db:
    ipam:
      config:
        - subnet: 172.222.222.0/30
  nw_nodes:
    ipam:
      config:
        - subnet: 172.123.123.0/25

services:
  services_db:
    image: 'mariadb:latest'
    ports:
      - "3306:3306"
    networks:
      - nw_services_db
    environment:
      MYSQL_ROOT_PASSWORD: p
    healthcheck:
      test: [ 'CMD', 'mysqladmin', '-uroot', '-pp', 'ping', '-h', '127.0.0.1' ]
      timeout: 1s
      retries: 30
  nodes_db:
    image: 'mariadb:latest'
    ports:
      - "3307:3307"
    networks:
      - nw_nodes_db
    environment:
      MYSQL_ROOT_PASSWORD: p
    healthcheck:
      test: [ 'CMD', 'mysqladmin', '-uroot', '-pp', 'ping', '-h', '127.0.0.1' ]
      timeout: 1s
      retries: 30
  node:
    build:
      context: .
      dockerfile: images/node/Dockerfile
    networks:
      - nw_nodes
      - nw_services_db
    depends_on:
      services_db:
        condition: service_healthy
