STATUS_OK = 200
STATUS_ERROR = 404

_DEFAULT_DB_USER = 'root'
_DEFAULT_DB_PASSWORD = 'p'
_DEFAULT_DB_NAME = 'ksurp'
_DEFAULT_DB_PORT = 3306

DB_NODE_USER = _DEFAULT_DB_USER
DB_NODE_PASSWORD = _DEFAULT_DB_PASSWORD
DB_NODE_NAME = _DEFAULT_DB_NAME
DB_NODE_HOST = '127.0.0.1'
DB_NODE_PORT = _DEFAULT_DB_PORT

DB_SERVICES_USER = _DEFAULT_DB_USER
DB_SERVICES_PASSWORD = _DEFAULT_DB_PASSWORD
DB_SERVICES_NAME = _DEFAULT_DB_NAME
DB_SERVICES_HOST = '172.111.111.2'
DB_SERVICES_PORT = _DEFAULT_DB_PORT
